# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1egaoe9LV8aYFY9x9MMT0K3ophbUtLZbu
"""

# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Step 1: Load the dataset
df = pd.read_csv('heart.csv')  # Make sure the CSV file path is correct

# Step 2: Explore the data (optional)
print(df.head())
print(df.info())
print(df['target'].value_counts())

# Step 3: Preprocessing
# Check for missing values
print(df.isnull().sum())  # Should ideally be zero; otherwise handle missing data here

# Step 4: Split dataset into features and target variable
X = df.drop('target', axis=1)
y = df['target']

# Step 5: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

# Step 6: Initialize the Gaussian Naive Bayes model
model = GaussianNB()

# Step 7: Train the model
model.fit(X_train, y_train)

# Step 8: Make predictions on the test set
y_pred = model.predict(X_test)

# Step 9: Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
